#
# Conditional build:
%bcond_without	pth	# without pth-based version of library
#
# TODO: separate pth version? disable by default (if !needed at all)?
Summary:	Cryptographic library based on the code from GnuPG
Summary(es):	Libgcrypt es una biblioteca general de desarrole embasada em GnuPG
Summary(pl):	Biblioteka kryptograficzna oparta na kodzie GnuPG
Summary(pt_BR):	libgcrypt é uma biblioteca de criptografia de uso geral baseada no GnuPG
Name:		libgcrypt
Version:	1.1.91
Release:	1
License:	LGPL
Group:		Libraries
Source0:	ftp://ftp.gnupg.org/gcrypt/alpha/libgcrypt/%{name}-%{version}.tar.gz
# Source0-md5:	8f3581d2d2a66c8f42b16f6ce13dedc3
Patch0:		%{name}-no_libnsl.patch
Patch1:		%{name}-info.patch
Patch2:		%{name}-am18.patch
URL:		http://www.gnu.org/directory/security/libgcrypt.html
BuildRequires:	autoconf >= 2.57
BuildRequires:	automake >= 1.7.6
BuildRequires:	binutils >= 2.12
BuildRequires:	gcc >= 3.2
BuildRequires:	libgpg-error-devel >= 0.5
BuildRequires:	libtool >= 1:1.4.3
%{?with_pth:BuildRequires:	pth-devel >= 1.2.0}
BuildRequires:	texinfo
BuildRoot:	%{tmpdir}/%{name}-%{version}-root-%(id -u -n)

%description
This is a general purpose cryptographic library based on the code from
GnuPG. It provides functions for all cryptograhic building blocks:
symmetric ciphers (AES, DES, Blowfish, CAST5, Twofish, Arcfour), hash
algorithms (MD5, RIPE-MD160, SHA-1, TIGER-192), MACs (HMAC for all
hash algorithms), public key algorithms (RSA, ElGamal, DSA), large
integer functions, random numbers and a lot of supporting functions.

%description -l pl
Ten pakiet zawiera bibliotekê kryptograficzn± ogólnego przeznaczenia,
opart± na kodzie GnuPG. Biblioteka ta dostarcza funkcje do wszystkich
podstawowych bloków kryptografii: szyfrów symetrycznych (AES, DES,
Blowfish, CAST5, Twofish, Acrfour), algorytmów mieszaj±cych (MD5,
RIPE-MD160, SHA-1, RIGER-192), MAC-ów (HMAC dla wszystkich algorytmów
mieszaj±cych), algorytmów klucza publicznego (RSA, ElGamal, DSA),
funkcji du¿ych liczb ca³kowitych, liczb losowych i wiele funkcji
pomocniczych.

%description -l pt_BR
Libgcrypt é uma biblioteca de criptografia de uso geral baseada no
GnuPG.

%package devel
Summary:	Header files etc to develop libgcrypt applications
Summary(es):	Archivos de desarrollo de libgcrypt
Summary(pl):	Pliki nag³ówkowe i inne do libgcrypt
Summary(pt_BR):	Arquivos de desenvolvimento da libgcrypt
Group:		Development/Libraries
Requires:	%{name} = %{version}
Requires:	libgpg-error-devel >= 0.1

%description devel
Header files etc to develop libgcrypt applications.

%description devel -l pl
Pliki nag³ówkowe i inne do libgcrypt.

%description devel -l pt_BR
Bibliotecas de desenvolvimento para libgcrypt.

%package static
Summary:	Static libgcrypt library
Summary(es):	Archivos de desarrollo de libgcrypt - estatico
Summary(pl):	Biblioteka statyczna libgcrypt
Summary(pt_BR):	Arquivos de desenvolvimento da libgcrypt - biblioteca estática
Group:		Development/Libraries
Requires:	%{name}-devel = %{version}

%description static
Static libgcrypt library.

%description static -l pl
Biblioteka statyczna libgcrypt.

%description static -l pt_BR
Bibliotecas de desenvolvimento para libgcrypt - estático.

%prep
%setup -q
%patch0 -p1
%patch1 -p1
%patch2 -p1

%build
%{__libtoolize}
%{__aclocal}
# ugly hack for am 1.8 (it tries to parse AC_CONFIG_LINKS
# but here they are autogenerated at configure time
%{__perl} -pi -e 's/(AC_CONFIG_LINKS)/x$1/' configure.ac
%{__automake}
%{__perl} -pi -e 's/x(AC_CONFIG_LINKS)/$1/' configure.ac
%{__autoconf}
%configure \
	--enable-static \
	%{!?with_pth:--without-pth}

%{__make}

%install
rm -rf $RPM_BUILD_ROOT

%{__make} install \
	DESTDIR=$RPM_BUILD_ROOT \
	m4datadir=%{_aclocaldir}

%clean
rm -rf $RPM_BUILD_ROOT

%post   -p /sbin/ldconfig
%postun -p /sbin/ldconfig

%post devel
[ ! -x /usr/sbin/fix-info-dir ] || /usr/sbin/fix-info-dir -c %{_infodir} >/dev/null 2>&1

%postun devel
[ ! -x /usr/sbin/fix-info-dir ] || /usr/sbin/fix-info-dir -c %{_infodir} >/dev/null 2>&1

%files
%defattr(644,root,root,755)
%doc AUTHORS THANKS NEWS README ChangeLog
%attr(755,root,root) %{_libdir}/lib*.so.*.*

%files devel
%defattr(644,root,root,755)
%attr(755,root,root) %{_bindir}/libgcrypt-config
%attr(755,root,root) %{_libdir}/lib*.so
%{_libdir}/lib*.la
%{_infodir}/*info*
%{_includedir}/*.h
%{_aclocaldir}/*

%files static
%defattr(644,root,root,755)
%{_libdir}/lib*.a
